# Generated by Django 4.2.6 on 2023-10-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="img/"),
        ),
    ]
