# Generated by Django 4.2.6 on 2023-10-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
